"""initial schema

Revision ID: 7589d10ed718
Revises: 
Create Date: 2026-09-10 22:18:53.446210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '7589d10ed718'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.Enum('summary', 'classification', 'clustering', 'verification', 'other', name='ai_request_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'skipped', name='ai_request_status_enum'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_requests_created_at', 'ai_requests', ['created_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('earthquake', 'news', 'network', 'other', name='event_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=300), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidence_enum'), nullable=True),
    sa.Column('status', sa.Enum('active', 'updated', 'resolved', 'closed', name='event_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_occurred_at', 'events', ['occurred_at'], unique=False)
    op.create_table('network_targets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.Enum('ping', 'tcp', 'http', 'dns', 'snmp', name='target_type_enum'), nullable=False),
    sa.Column('target', sa.String(length=300), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_network_targets_enabled', 'network_targets', ['enabled'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('source_type', sa.Enum('rss', 'api', 'scraper', name='source_type_enum'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('feed_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url', name='uq_sources_base_url')
    )
    op.create_index('ix_sources_enabled', 'sources', ['enabled'], unique=False)
    op.create_index('ix_sources_feed_url', 'sources', ['feed_url'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('processing_status', sa.Enum('raw', 'deduplicated', 'clustered', 'verified', 'failed', name='processing_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_articles_url')
    )
    op.create_index('ix_articles_content_hash', 'articles', ['content_hash'], unique=False)
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_source_id', 'articles', ['source_id'], unique=False)
    op.create_table('earthquakes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('magnitude', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('depth_km', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('place', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_earthquakes_source_external_id')
    )
    op.create_index('ix_earthquakes_occurred_at', 'earthquakes', ['occurred_at'], unique=False)
    op.create_table('network_checks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('up', 'down', 'timeout', 'error', name='check_status_enum'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['network_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_checks_checked_at'), 'network_checks', ['checked_at'], unique=False)
    op.create_index('ix_network_checks_target_id', 'network_checks', ['target_id'], unique=False)
    op.create_table('event_articles',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type', sa.Enum('primary', 'related', 'duplicate', 'update', name='relation_type_enum'), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'article_id'),
    sa.UniqueConstraint('event_id', 'article_id', name='uq_event_articles')
    )
    op.create_index('ix_event_articles_article_id', 'event_articles', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_articles_article_id', table_name='event_articles')
    op.drop_table('event_articles')
    op.drop_index('ix_network_checks_target_id', table_name='network_checks')
    op.drop_index(op.f('ix_network_checks_checked_at'), table_name='network_checks')
    op.drop_table('network_checks')
    op.drop_index('ix_earthquakes_occurred_at', table_name='earthquakes')
    op.drop_table('earthquakes')
    op.drop_index('ix_articles_source_id', table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_index('ix_articles_content_hash', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_sources_feed_url', table_name='sources')
    op.drop_index('ix_sources_enabled', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_network_targets_enabled', table_name='network_targets')
    op.drop_table('network_targets')
    op.drop_index('ix_events_occurred_at', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_ai_requests_created_at', table_name='ai_requests')
    op.drop_table('ai_requests')
    # ### end Alembic commands ###