"""add weather locations and forecasts

Revision ID: d0ac409ea156
Revises: 7589d10ed718
Create Date: 2026-09-10 23:33:54.993408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0ac409ea156'
down_revision: Union[str, None] = '7589d10ed718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_locations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('adm1', sa.String(length=50), nullable=True),
    sa.Column('adm2', sa.String(length=50), nullable=True),
    sa.Column('adm3', sa.String(length=50), nullable=True),
    sa.Column('adm4', sa.String(length=50), nullable=False),
    sa.Column('provinsi', sa.String(length=200), nullable=True),
    sa.Column('kotkab', sa.String(length=200), nullable=True),
    sa.Column('kecamatan', sa.String(length=200), nullable=True),
    sa.Column('desa', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adm4', name='uq_weather_locations_adm4')
    )
    op.create_index('ix_weather_locations_enabled', 'weather_locations', ['enabled'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_datetime', sa.DateTime(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('weather_description', sa.String(length=200), nullable=True),
    sa.Column('weather_description_en', sa.String(length=100), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Integer(), nullable=True),
    sa.Column('wind_dir', sa.String(length=10), nullable=True),
    sa.Column('wind_to_dir', sa.String(length=10), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('visibility_text', sa.String(length=60), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['weather_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'forecast_datetime', name='uq_weather_forecasts')
    )
    op.create_index('ix_weather_forecasts_forecast_datetime', 'weather_forecasts', ['forecast_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_forecasts_forecast_datetime', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index('ix_weather_locations_enabled', table_name='weather_locations')
    op.drop_table('weather_locations')
    # ### end Alembic commands ###