"""add alert tables

Revision ID: d1ad0b68dba5
Revises: c4c5fbcb1abe
Create Date: 2026-09-11 05:07:01.207996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'd1ad0b68dba5'
down_revision: Union[str, None] = 'c4c5fbcb1abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('priority', sa.Enum('p1', 'p2', 'p3', 'p4', name='alert_priority_enum'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_signature', sa.String(length=300), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_alerts_event_id')
    )
    op.create_index('ix_alerts_priority', 'alerts', ['priority'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('alert_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('initial', 'update', 'severity', 'resolved', name='alert_message_kind_enum'), nullable=False),
    sa.Column('priority', sa.Enum('p1', 'p2', 'p3', 'p4', name='alert_message_priority_enum'), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('body', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_messages_created_at', 'alert_messages', ['created_at'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_message_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('delivered', 'skipped', 'failed', name='alert_delivery_status_enum'), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_message_id'], ['alert_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_deliveries_channel', 'alert_deliveries', ['channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_deliveries_channel', table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index('ix_alert_messages_created_at', table_name='alert_messages')
    op.drop_table('alert_messages')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_priority', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###